[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['rm -rf node_modules package-lock.json', 'npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npm start'
